### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "QwertyTest123!"
}

### Register again — should be 409
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "QwertyTest123!"
}

### Password does not meet minimum requirements - should be 400
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "weakpass"
}

### Missing password — should be 400
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "nopassword@email.com"
}

### Missing email — should be 400
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "password": "NoEmailIncluded123!"
}