@base = https://localhost:5000/api
@password = QwertyTest123!

### Register a new freelancer - should be 201 (401 if run again)
POST {{base}}/auth/register
Content-Type: application/json

{
  "email": "freelancer@test.com",
  "password": "{{password}}",
  "name": "Free",
  "surname": "Lancer",
  "displayName": "Lancer Designs",
  "role": "freelancer"
}

### Register a client - should be 201 (401 if run again)
POST {{base}}/auth/register
Content-Type: application/json

{
  "email": "client@test.com",
  "password": "{{password}}",
  "name": "Cli",
  "surname": "Ent",
  "displayName": "Client",
  "role": "client"
}

### Password does not meet minimum requirements - should be 400
POST https://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "weakpass"
}

### Missing password - should be 400
POST https://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "nopassword@email.com"
}

### Missing email - should be 400
POST https://localhost:5000/api/auth/register
Content-Type: application/json

{
  "password": "NoEmailIncluded123!"
}

### Bad route - should be 404
GET https://localhost:5000/api/auth/whereami


### Login as freelancer - should be 200
# @name freelancerLogin
POST {{base}}/auth/login
Content-Type: application/json

{ "email": "freelancer@test.com", "password": "{{password}}" }

### Login as client - should be 200
# @name clientLogin
POST {{base}}/auth/login
Content-Type: application/json

{ "email": "client@test.com", "password": "{{password}}" }

### Incorrect email for Login - should be 401
POST  {{base}}/auth/login
Content-Type: application/json

{
  "email": "wrongemail@email.com",
  "password": "QwertyTest123!"
}

### Incorrect pasword for Login - should be 401
POST  {{base}}/auth/login
Content-Type: application/json

{
  "email": "wrongemail@email.com",
  "password": "Wrongpassword123!"
}


### Missing email for Login - should be 401
POST  https://localhost:5000/api/auth/login
Content-Type: application/json

{
  "password": "QwertyTest123!"
}


### Missing pasword for Login - should be 401
POST  https://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "wrongemail@email.com"
}

### Not an email for Login - should be 401
POST  https://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "wrongemailemail.com",
  "password": "QwertyTest123!"
}

### ========= Check protected route tests =========

### Register the user
POST https://localhost:5000/api/auth/register
Content-Type: application/json

{ "email": "login.test@email.com", "password": "QwertyTest123!" }

### Log the user in to get token
# @name login
POST https://localhost:5000/api/auth/login
Content-Type: application/json

{ "email": "login.test@email.com", "password": "QwertyTest123!" }

### Get current user = should be 200
GET https://localhost:5000/api/users/me
Authorization: Bearer {{login.response.body.token}}

### No token - should be 401
GET https://localhost:5000/api/users/me

### Wtong token - should be 401
GET https://localhost:5000/api/users/me
Authorization: Bearer very.much.fake.token

### Create a gig as the freelancer - should be 201
POST {{base}}/gigs
Content-Type: application/json
Authorization: Bearer {{freelancerLogin.response.body.token}}

{
  "title": "Logo design",
  "category": "design",
  "description": "A logo or something idk",
  "tiers": [
    { "title": "Basic", "priceCents": 50000 },
    { "title": "Premium", "description": "Three concepts", "priceCents": 120000 }
  ]
}

### List freelancer's gigs - should be 200
GET {{base}}/gigs/mygigs
Authorization: Bearer {{freelancerLogin.response.body.token}}